send:
  fields:
    event:
      required: true
      example: '0b11009e00e6116202020070'
      selector:
        text:

update_cover_position:
  target:
    entity:
      domain: cover
  fields:
    position:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'
    tilt_position:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'
    state:
      required: true
      selector:
        text:
